FROM qtangs/sagemaker-notebook-base

# ==================================================================
# Create environment(s)
# ------------------------------------------------------------------

USER $NB_UID

COPY envs $HOME/envs/

# Fix permissions on $HOME/envs/ as root
USER root
RUN fix-permissions $HOME/envs/

USER $NB_UID

RUN $HOME/envs/create_env_file.sh pytorch_p36 && \
    $HOME/envs/create_env.sh pytorch_p36